
proxy: !nftables {}

connectivity: !wireguard
  manual_node:
    pod_cidrs:
    - "192.168.242.0/28"
  on_create:
  - !nft_chain
    table: knls
    chain: wireguard
    rules: |-
      # ...

dns: !internal
  on_listen:
  - !exec
    cmd: sh
    args:
    - -c
    - echo nameserver 127.0.0.1:53 >/host-resolv.conf
  cluster_domain: cluster.local

